language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
script:
  - julia --code-coverage test/runtests.jl
after_success:
  - julia -e 'cd(Pkg.dir("ErrorFreeTransforms")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
